language: python

python:
  - "2.7.8"
  - "2.7.9"
  - "2.7.10"
  - "2.7.11"
  - "2.7.12"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -e .
  - pip install codecov

script:
  - python runtests.py
  - coverage run runtests.py

after_success:
- bash <(curl -s https://codecov.io/bash)

